"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'id' | 'en' | 'ms'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

type TranslationMap = Record<string, Record<string, string>>

// Translation data
const translations: TranslationMap = {
  id: {
    // Header
    'header.title': 'MAZA FINANCE',
    'header.subtitle': 'Solusi Keuangan',
    'header.home': 'Beranda',
    'header.dashboard': 'Dashboard',
    'header.management': 'Manajemen',
    'header.games': 'Permainan',
    'header.pointsStore': 'Toko Poin',
    'header.aiChat': 'AI Chat',
    'header.news': 'Berita',
    'header.signIn': 'Masuk',
    'header.getStarted': 'Mulai Sekarang',

    // Language switcher
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English',
    'language.malay': 'Bahasa Melayu',

    // Common
    'common.back': 'Kembali',
    'common.search': 'Cari',
    'common.loadMore': 'Muat Lebih Banyak',
    'common.viewAll': 'Lihat Semua',
    'common.readMore': 'Baca Selengkapnya',
    'common.play': 'Main',
    'common.comingSoon': 'Segera Hadir',
    'common.subscribe': 'Berlangganan Gratis',
    'common.submit': 'Kirim',
    'common.send': 'Kirim',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.loading': 'Memuat...',
    'common.error': 'Terjadi kesalahan',
    'common.disclaimer': 'Informasi yang diberikan hanya untuk edukasi. Konsultasikan dengan penasihat keuangan profesional sebelum membuat keputusan investasi.',
    'common.points': 'Poin',
    'common.availableToSpend': 'Tersedia untuk ditukar',
    'common.earned': 'Didapat',
    'common.spent': 'Digunakan',
    'common.lifetime': 'Akumulasi',
    'common.streak': 'Rekor',
    'common.daily': 'Harian',
    'common.newGame': 'Game Baru',
    'common.help': 'Bantuan',
    'common.stats': 'Statistik',
    'common.dailyMode': 'Mode Harian',
    'common.freeMode': 'Mode Bebas',
    'common.quit': 'Keluar',
    'common.tryAgain': 'Coba Lagi',
    'common.next': 'Lanjut',
    'common.skip': 'Lewati',
    'common.finish': 'Selesai',
    'common.score': 'Skor',
    'common.correct': 'Benar',
    'common.incorrect': 'Salah',
    'common.yourScore': 'Skor Anda',
    'common.gamesPlayed': 'Game Dimainkan',
    'common.pointsCollected': 'Poin Terkumpul',
    'common.milestonesReached': 'Milestone Tercapai',
    'common.budget': 'Budget',

    // Landing
    'landing.hero.title': 'Kuasai Uangmu, Kuasai Masa Depanmu',
    'landing.hero.subtitle':
      'Kelola keuangan jadi mudah: catat otomatis, investasi cerdas, dan belajar lewat game seru — semua dibantu AI. Mulai gratis tanpa ribet.',
    'landing.hero.ctaPrimary': 'Mulai Gratis Sekarang',
    'landing.hero.ctaSecondary': 'Lihat Cara Kerjanya',

    // News
    'news.hero.badge': 'Berita Finansial Terkini',
    'news.hero.titleLine1': 'Pasar Bergerak Cepat?',
    'news.hero.titleLine2': 'Kamu Tetap Tenang.',
    'news.hero.subtitle':
      'Berita saham, kripto, dan ekonomi yang ringkas dan mudah dipahami — langsung tahu apa yang harus kamu lakukan.',
    'news.hero.searchPlaceholder': 'Cari berita, topik, atau kata kunci...',
    'news.hero.statArticles': 'Artikel Terbaru',
    'news.hero.statReaders': 'Pembaca Aktif',
    'news.hero.statUpdates': 'Update Realtime',
    'news.breaking': 'Breaking News',
    'news.latest': 'Berita Terbaru',
    'news.categories': 'Kategori Berita',
    'news.trending': 'Topik Hangat',
    'news.newsletter.title': 'Newsletter Harian',
    'news.newsletter.description': 'Dapatkan ringkasan berita finansial langsung di email Anda',
    'news.readMinutes': 'menit baca',
    'news.views': 'x dilihat',
    'news.takeQuiz': 'Uji pemahamanmu',
    'news.relatedGame': 'Game Terkait',
    'news.marketNews': 'Berita Pasar',
    'news.source': 'Sumber',
    'news.noResults': 'Tidak ada berita yang ditemukan. Coba kata kunci lain.',
    'news.searchResults': 'Hasil pencarian',
    'news.category.stock': 'Pasar Saham',
    'news.category.crypto': 'Cryptocurrency',
    'news.category.economy': 'Ekonomi',
    'news.category.investment': 'Investasi',
    'news.category.fintech': 'Fintech',
    'news.category.banking': 'Perbankan',

    // Newsletter
    'newsletter.title': 'Newsletter Finansial',
    'newsletter.subtitle': 'Dapatkan insight terbaru tentang pasar keuangan, tips investasi, dan berita finansial langsung di inbox Anda',
    'newsletter.subscribeTitle': 'Berlangganan Newsletter',
    'newsletter.subscribeDescription': 'Pilih jenis newsletter yang ingin Anda terima',
    'newsletter.emailLabel': 'Alamat Email',
    'newsletter.choosePlans': 'Pilih Newsletter:',
    'newsletter.popular': 'Populer',
    'newsletter.subscribeNow': 'Berlangganan Sekarang',
    'newsletter.whyTitle': 'Mengapa Berlangganan?',
    'newsletter.ctaSubscribers': 'Subscriber Aktif',
    'newsletter.ctaRating': 'Rating Newsletter',
    'newsletter.ctaOpenRate': 'Open Rate',
    'newsletter.ctaForever': 'Selamanya',
    'newsletter.successTitle': 'Berhasil Berlangganan!',
    'newsletter.successDescription': 'Terima kasih telah berlangganan newsletter kami. Email konfirmasi telah dikirim ke {email}',
    'newsletter.activeSubscriptions': 'Langganan Aktif:',
    'newsletter.changePlan': 'Ubah Langganan',
    'newsletter.backToNews': 'Kembali ke Berita',
    'newsletter.premiumTitle': 'Premium Newsletter',
    'newsletter.premiumDescription': 'Upgrade ke premium untuk mendapatkan analisis eksklusif, research report, dan akses ke webinar bulanan',
    'newsletter.premiumCta': 'Pelajari Premium',
    'newsletter.termsPrefix': 'Saya setuju dengan',
    'newsletter.termsLink': 'syarat dan ketentuan',
    'newsletter.termsAnd': 'serta',
    'newsletter.privacyLink': 'kebijakan privasi',

    // Games
    'games.yourPoints': 'Poin Gaming Anda',
    'games.visitStore': 'Kunjungi Toko',
    'games.popular': 'Game Populer',
    'games.pointsStore': 'Toko Poin',
    'games.reward': 'Reward',
    'games.achievements': 'Pencapaian Anda',
    'games.done': 'Selesai',
    'games.forcle': 'FORDLE',
    'games.forcle.desc':
      'Game kata interaktif tentang istilah keuangan. Seru untuk menambah kosakata finansialmu.',
    'games.budgetMaster': 'Budget Master',
    'games.budgetMaster.desc': 'Kelola budget bulanan dan capai target keuangan dengan gameplay yang seru',
    'games.investmentTycoon': 'Investment Tycoon',
    'games.investmentTycoon.desc': 'Bangun portofolio investasi dan jadilah miliarder virtual',
    'games.savingChallenge': 'Saving Challenge',
    'games.savingChallenge.desc': 'Tantangan menabung harian dengan reward menarik',
    'games.cryptoQuest': 'Crypto Quest',
    'games.cryptoQuest.desc': 'Jelajahi dunia cryptocurrency dengan aman dalam simulasi',
    'games.debtDestroyer': 'Debt Destroyer',
    'games.debtDestroyer.desc': 'Strategi melunasi hutang dengan cara yang menyenangkan',
    'games.quizArena': 'FinQuiz Arena',
    'games.quizArena.desc': 'Uji pengetahuan finansialmu dalam kuis serba cepat',
    'games.achievement.firstInvestment': 'Investasi Pertama',
    'games.achievement.firstInvestment.desc': 'Buat investasi pertama Anda',
    'games.achievement.budgetPro': 'Budget Pro',
    'games.achievement.budgetPro.desc': 'Kelola budget selama 30 hari',
    'games.achievement.savingStreak': 'Saving Streak',
    'games.achievement.savingStreak.desc': 'Menabung konsisten 7 hari',
    'games.achievement.quizMaster': 'Quiz Master',
    'games.achievement.quizMaster.desc': 'Jawab 100 pertanyaan dengan benar',

    // Quiz
    'quiz.title': 'FinQuiz Arena',
    'quiz.subtitle': 'Jawab 10 soal, buktikan kamu paham uang — dan raih poin untuk ditukar hadiah.',
    'quiz.start': 'Mulai Kuis',
    'quiz.next': 'Soal Berikutnya',
    'quiz.category': 'Kategori',
    'quiz.difficulty.easy': 'Mudah',
    'quiz.difficulty.medium': 'Sedang',
    'quiz.difficulty.hard': 'Sulit',
    'quiz.selectCategory': 'Pilih Kategori',
    'quiz.selectDifficulty': 'Pilih Tingkat Kesulitan',
    'quiz.anyCategory': 'Semua Kategori',
    'quiz.question': 'Soal',
    'quiz.of': 'dari',
    'quiz.correctAnswer': 'Benar!',
    'quiz.wrongAnswer': 'Salah! Jawaban yang benar:',
    'quiz.completed': 'Kuis Selesai!',
    'quiz.correctCount': 'jawaban benar',
    'quiz.pointsEarned': 'Poin didapat',
    'quiz.playAgain': 'Main Lagi',
    'quiz.relatedNews': 'Berita Terkait',
    'quiz.loadingQuestions': 'Menyiapkan soal...',
    'quiz.errorLoad': 'Gagal memuat soal. Coba lagi.',

    // Dashboard
    'dashboard.title': 'Dashboard Keuangan',
    'dashboard.subtitle': 'Pengeluaran, investasi, target — semua keuanganmu dalam satu tempat.',
    'dashboard.expenses': 'Pengeluaran',
    'dashboard.income': 'Pemasukan',
    'dashboard.investments': 'Investasi',
    'dashboard.savings': 'Tabungan',
    'dashboard.features': 'Fitur Unggulan',
    'dashboard.projections': 'Proyeksi Keuangan',
    'dashboard.qrPayment': 'Pembayaran QR',
    'dashboard.assistant': 'Asisten AI',

    // Management
    'management.title': 'Manajemen Keuangan',
    'management.transactions': 'Transaksi',
    'management.addTransaction': 'Tambah Transaksi',
    'management.riskAnalysis': 'Analisis Risiko',
    'management.portfolioAnalysis': 'Analisis Portofolio',
    'management.dashboard': 'Ringkasan Keuangan',
    'management.chatbot': 'Asisten AI',

    // Portfolio
    'portfolio.title': 'Portofolio Investasi',
    'portfolio.totalValue': 'Total Nilai',
    'portfolio.totalReturn': 'Total Return',
    'portfolio.dailyChange': 'Perubahan Hari Ini',
    'portfolio.holdings': 'Kepemilikan',
    'portfolio.performance': 'Kinerja',

    // Savings
    'savings.title': 'Target Tabungan',
    'savings.newGoal': 'Target Baru',
    'savings.currentAmount': 'Jumlah Saat Ini',
    'savings.targetAmount': 'Target',
    'savings.progress': 'Progres',
    'savings.tracker.title': 'Pelacak Tabungan',
    'savings.addEntry': 'Tambah Catatan',

    // Points
    'points.title': 'Toko Poin',
    'points.balance': 'Saldo Poin',
    'points.available': 'Poin Tersedia',
    'points.redeem': 'Tukar',
    'points.history': 'Riwayat Poin',
    'points.topUp': 'Top Up',
    'points.vouchers': 'Voucher',
    'points.purchase': 'Beli',
    'points.myVouchers': 'Voucher Saya',
    'points.noVouchers': 'Belum Ada Voucher',
    'points.noVouchersDesc': 'Beli voucher untuk melihatnya di sini',
    'points.browseVouchers': 'Jelajahi Voucher',
    'points.insufficientPoints': 'Poin Tidak Cukup',
    'points.confirmPurchase': 'Konfirmasi Pembelian',
    'points.confirmTopUp': 'Konfirmasi Top-Up',
    'points.processingTime': 'Waktu proses: 1-24 jam',
    'points.validity': 'hari masa berlaku',
    'points.used': 'Sudah Dipakai',
    'points.expired': 'Kedaluwarsa',
    'points.daysLeft': 'hari tersisa',
    'points.useVoucher': 'Gunakan Voucher',
    'points.alreadyUsed': 'Sudah Digunakan',

    // AI Chat
    'ai.title': 'Asisten Keuangan AI',
    'ai.subtitle': 'Konsultasi keuangan dan investasi dengan AI yang komprehensif dan real-time',
    'ai.placeholder': 'Tanyakan tentang investasi, saham, cryptocurrency, perencanaan keuangan...',
    'ai.quickTitle': 'Pertanyaan Cepat',
    'ai.analyzing': 'AI sedang menganalisis...',
    'ai.online': 'Online',
    'ai.poweredBy': 'Ditenagai AI Canggih',
    'ai.welcome':
      'Selamat datang di MAZA Finance AI!\n\nSaya asisten AI keuangan yang siap membantu Anda dengan:\n\n- Analisis Investasi & Saham\n- Perencanaan Keuangan Personal\n- Cryptocurrency & Trading\n- Analisis Portfolio\n- Strategi Investasi Jangka Panjang\n\nAda yang ingin Anda tanyakan?',
    'ai.quick.stocks': 'Analisis saham BBRI terbaru',
    'ai.quick.currency': 'Kurs USD ke IDR hari ini',
    'ai.quick.portfolio': 'Strategi diversifikasi portfolio',
    'ai.quick.news': 'Berita pasar modal terkini',
    'ai.conversations': 'Percakapan',
    'ai.newConversation': 'Percakapan Baru',
    'ai.signInTitle': 'Silakan Masuk',
    'ai.signInPrompt': 'Anda harus masuk untuk menggunakan Asisten AI Finansial.',
    'ai.realtimeBadge': 'Data Real-time',
    'ai.assistantName': 'Maza Finance AI',
    'ai.assistantDesc': 'Asisten Kecerdasan Finansial',

    // Footer
    'footer.tagline': 'Kebebasan finansial dimulai sejak muda. Kami buat simpel, cerdas, dan seru.',
    'footer.features': 'Fitur',
    'footer.resources': 'Sumber',
    'footer.download': 'Download Aplikasi',
    'footer.getApp': 'Dapatkan Maza Finance di perangkat Anda',
    'footer.expenseTracking': 'Pelacakan Pengeluaran',
    'footer.aiAssistant': 'Asisten AI Keuangan',
    'footer.investmentGames': 'Game Investasi',
    'footer.financialProjections': 'Proyeksi Keuangan',
    'footer.blog': 'Blog',
    'footer.tutorials': 'Tutorial',
    'footer.financialTips': 'Tips Finansial',
    'footer.helpCenter': 'Pusat Bantuan',
    'footer.appStore': 'App Store',
    'footer.playStore': 'Play Store',
    'footer.copyright': '© 2024 Maza Finance. Semua hak dilindungi. Layanan perbankan disediakan oleh bank mitra kami.',
  },
  en: {
    // Header
    'header.title': 'MAZA FINANCE',
    'header.subtitle': 'Financial Solutions',
    'header.home': 'Home',
    'header.dashboard': 'Dashboard',
    'header.management': 'Management',
    'header.games': 'Games',
    'header.pointsStore': 'Points Store',
    'header.aiChat': 'AI Chat',
    'header.news': 'News',
    'header.signIn': 'Sign In',
    'header.getStarted': 'Get Started',

    // Language switcher
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English',
    'language.malay': 'Bahasa Melayu',

    // Common
    'common.back': 'Back',
    'common.search': 'Search',
    'common.loadMore': 'Load More',
    'common.viewAll': 'View All',
    'common.readMore': 'Read More',
    'common.play': 'Play',
    'common.comingSoon': 'Coming Soon',
    'common.subscribe': 'Subscribe Free',
    'common.submit': 'Submit',
    'common.send': 'Send',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.disclaimer': 'Information provided is for educational purposes only. Consult a professional financial advisor before making any investment decisions.',
    'common.points': 'Points',
    'common.availableToSpend': 'Available to spend',
    'common.earned': 'Earned',
    'common.spent': 'Spent',
    'common.lifetime': 'Lifetime',
    'common.streak': 'Streak',
    'common.daily': 'Daily',
    'common.newGame': 'New Game',
    'common.help': 'Help',
    'common.stats': 'Stats',
    'common.dailyMode': 'Daily Mode',
    'common.freeMode': 'Free Mode',
    'common.quit': 'Quit',
    'common.tryAgain': 'Try Again',
    'common.next': 'Next',
    'common.skip': 'Skip',
    'common.finish': 'Finish',
    'common.score': 'Score',
    'common.correct': 'Correct',
    'common.incorrect': 'Incorrect',
    'common.yourScore': 'Your Score',
    'common.gamesPlayed': 'Games Played',
    'common.pointsCollected': 'Points Collected',
    'common.milestonesReached': 'Milestones Reached',
    'common.budget': 'Budget',

    // Landing
    'landing.hero.title': 'Master Your Money, Master Your Future',
    'landing.hero.subtitle':
      'Managing money made easy: automatic tracking, smarter investing, and fun learning games — all powered by AI.',
    'landing.hero.ctaPrimary': 'Start Free Now',
    'landing.hero.ctaSecondary': 'See How It Works',

    // News
    'news.hero.badge': 'Latest Financial News',
    'news.hero.titleLine1': 'Market Moving Fast?',
    'news.hero.titleLine2': 'Stay One Step Ahead.',
    'news.hero.subtitle':
      'Concise, easy-to-read stock, crypto, and economy news — so you always know what to do next.',
    'news.hero.searchPlaceholder': 'Search news, topics, or keywords...',
    'news.hero.statArticles': 'Latest Articles',
    'news.hero.statReaders': 'Active Readers',
    'news.hero.statUpdates': 'Real-time Updates',
    'news.breaking': 'Breaking News',
    'news.latest': 'Latest News',
    'news.categories': 'News Categories',
    'news.trending': 'Trending Topics',
    'news.newsletter.title': 'Daily Newsletter',
    'news.newsletter.description': 'Get financial news summaries straight to your inbox',
    'news.readMinutes': 'min read',
    'news.views': 'views',
    'news.takeQuiz': 'Test your knowledge',
    'news.relatedGame': 'Related Game',
    'news.marketNews': 'Market News',
    'news.source': 'Source',
    'news.noResults': 'No news found. Try another keyword.',
    'news.searchResults': 'Search results',
    'news.category.stock': 'Stock Market',
    'news.category.crypto': 'Cryptocurrency',
    'news.category.economy': 'Economy',
    'news.category.investment': 'Investment',
    'news.category.fintech': 'Fintech',
    'news.category.banking': 'Banking',
    'newsletter.title': 'Financial Newsletter',
    'newsletter.subtitle': 'Get the latest insights on financial markets, investing tips, and finance news straight to your inbox',
    'newsletter.subscribeTitle': 'Subscribe to Newsletter',
    'newsletter.subscribeDescription': 'Choose which newsletters you want to receive',
    'newsletter.emailLabel': 'Email Address',
    'newsletter.choosePlans': 'Select Newsletters:',
    'newsletter.popular': 'Popular',
    'newsletter.subscribeNow': 'Subscribe Now',
    'newsletter.whyTitle': 'Why Subscribe?',
    'newsletter.ctaSubscribers': 'Active Subscribers',
    'newsletter.ctaRating': 'Newsletter Rating',
    'newsletter.ctaOpenRate': 'Open Rate',
    'newsletter.ctaForever': 'Forever',
    'newsletter.successTitle': 'Successfully Subscribed!',
    'newsletter.successDescription': 'Thank you for subscribing to our newsletter. A confirmation email has been sent to {email}',
    'newsletter.activeSubscriptions': 'Active Subscriptions:',
    'newsletter.changePlan': 'Change Plan',
    'newsletter.backToNews': 'Back to News',
    'newsletter.premiumTitle': 'Premium Newsletter',
    'newsletter.premiumDescription': 'Upgrade to premium for exclusive analysis, research reports, and access to monthly webinars',
    'newsletter.premiumCta': 'Learn Premium',
    'newsletter.termsPrefix': 'I agree to the',
    'newsletter.termsLink': 'terms and conditions',
    'newsletter.termsAnd': 'and',
    'newsletter.privacyLink': 'privacy policy',

    // Games
    'games.yourPoints': 'Your Gaming Points',
    'games.visitStore': 'Visit Store',
    'games.popular': 'Popular Games',
    'games.pointsStore': 'Points Store',
    'games.reward': 'Reward',
    'games.achievements': 'Your Achievements',
    'games.done': 'Done',
    'games.forcle': 'FORDLE',
    'games.forcle.desc':
      'An interactive word game about financial terms. Fun way to grow your financial vocabulary.',
    'games.budgetMaster': 'Budget Master',
    'games.budgetMaster.desc': 'Manage a monthly budget and hit financial goals with fun gameplay',
    'games.investmentTycoon': 'Investment Tycoon',
    'games.investmentTycoon.desc': 'Build an investment portfolio and become a virtual billionaire',
    'games.savingChallenge': 'Saving Challenge',
    'games.savingChallenge.desc': 'Daily saving challenges with attractive rewards',
    'games.cryptoQuest': 'Crypto Quest',
    'games.cryptoQuest.desc': 'Explore the crypto world safely through simulation',
    'games.debtDestroyer': 'Debt Destroyer',
    'games.debtDestroyer.desc': 'Fun strategies to pay off debt',
    'games.quizArena': 'FinQuiz Arena',
    'games.quizArena.desc': 'Test your financial knowledge in a fast-paced quiz',
    'games.achievement.firstInvestment': 'First Investment',
    'games.achievement.firstInvestment.desc': 'Make your first investment',
    'games.achievement.budgetPro': 'Budget Pro',
    'games.achievement.budgetPro.desc': 'Manage a budget for 30 days',
    'games.achievement.savingStreak': 'Saving Streak',
    'games.achievement.savingStreak.desc': 'Save consistently for 7 days',
    'games.achievement.quizMaster': 'Quiz Master',
    'games.achievement.quizMaster.desc': 'Answer 100 questions correctly',

    // Quiz
    'quiz.title': 'FinQuiz Arena',
    'quiz.subtitle': 'Answer 10 questions, prove you get money — and earn points to redeem for rewards.',
    'quiz.start': 'Start Quiz',
    'quiz.next': 'Next Question',
    'quiz.category': 'Category',
    'quiz.difficulty.easy': 'Easy',
    'quiz.difficulty.medium': 'Medium',
    'quiz.difficulty.hard': 'Hard',
    'quiz.selectCategory': 'Select Category',
    'quiz.selectDifficulty': 'Select Difficulty',
    'quiz.anyCategory': 'All Categories',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.correctAnswer': 'Correct!',
    'quiz.wrongAnswer': 'Wrong! Correct answer:',
    'quiz.completed': 'Quiz Completed!',
    'quiz.correctCount': 'correct answers',
    'quiz.pointsEarned': 'Points earned',
    'quiz.playAgain': 'Play Again',
    'quiz.relatedNews': 'Related News',
    'quiz.loadingQuestions': 'Preparing questions...',
    'quiz.errorLoad': 'Failed to load questions. Try again.',

    // Dashboard
    'dashboard.title': 'Finance Dashboard',
    'dashboard.subtitle': 'Expenses, investments, goals — all your money in one place.',
    'dashboard.expenses': 'Expenses',
    'dashboard.income': 'Income',
    'dashboard.investments': 'Investments',
    'dashboard.savings': 'Savings',
    'dashboard.features': 'Key Features',
    'dashboard.projections': 'Financial Projections',
    'dashboard.qrPayment': 'QR Payment',
    'dashboard.assistant': 'AI Assistant',

    // Management
    'management.title': 'Financial Management',
    'management.transactions': 'Transactions',
    'management.addTransaction': 'Add Transaction',
    'management.riskAnalysis': 'Risk Analysis',
    'management.portfolioAnalysis': 'Portfolio Analysis',
    'management.dashboard': 'Finance Summary',
    'management.chatbot': 'AI Assistant',

    // Portfolio
    'portfolio.title': 'Investment Portfolio',
    'portfolio.totalValue': 'Total Value',
    'portfolio.totalReturn': 'Total Return',
    'portfolio.dailyChange': 'Today Change',
    'portfolio.holdings': 'Holdings',
    'portfolio.performance': 'Performance',

    // Savings
    'savings.title': 'Savings Goals',
    'savings.newGoal': 'New Goal',
    'savings.currentAmount': 'Current Amount',
    'savings.targetAmount': 'Target',
    'savings.progress': 'Progress',
    'savings.tracker.title': 'Savings Tracker',
    'savings.addEntry': 'Add Entry',

    // Points
    'points.title': 'Points Store',
    'points.balance': 'Points Balance',
    'points.available': 'Available Points',
    'points.redeem': 'Redeem',
    'points.history': 'Points History',
    'points.topUp': 'Top Up',
    'points.vouchers': 'Vouchers',
    'points.purchase': 'Purchase',
    'points.myVouchers': 'My Vouchers',
    'points.noVouchers': 'No Vouchers Yet',
    'points.noVouchersDesc': 'Purchase vouchers to see them here',
    'points.browseVouchers': 'Browse Vouchers',
    'points.insufficientPoints': 'Insufficient Points',
    'points.confirmPurchase': 'Confirm Purchase',
    'points.confirmTopUp': 'Confirm Top-Up',
    'points.processingTime': 'Processing time: 1-24 hours',
    'points.validity': 'days validity',
    'points.used': 'Used',
    'points.expired': 'Expired',
    'points.daysLeft': 'days left',
    'points.useVoucher': 'Use Voucher',
    'points.alreadyUsed': 'Already Used',

    // AI Chat
    'ai.title': 'AI Financial Assistant',
    'ai.subtitle': 'Consult on finance and investing with a comprehensive, real-time AI',
    'ai.placeholder': 'Ask about investing, stocks, cryptocurrency, financial planning...',
    'ai.quickTitle': 'Quick Questions',
    'ai.analyzing': 'AI is analyzing...',
    'ai.online': 'Online',
    'ai.poweredBy': 'Powered by Advanced AI',
    'ai.welcome':
      'Welcome to MAZA Finance AI!\n\nI am your financial AI assistant, ready to help with:\n\n- Investment & Stock Analysis\n- Personal Financial Planning\n- Cryptocurrency & Trading\n- Portfolio Analysis\n- Long-term Investment Strategies\n\nWhat would you like to ask today?',
    'ai.quick.stocks': 'Show me BBRI stock price',
    'ai.quick.currency': 'USD to IDR exchange rate',
    'ai.quick.portfolio': 'Analyze my portfolio',
    'ai.quick.news': 'Latest market news',
    'ai.conversations': 'Conversations',
    'ai.newConversation': 'New Conversation',
    'ai.signInTitle': 'Please Sign In',
    'ai.signInPrompt': 'You need to be signed in to use the AI Financial Assistant.',
    'ai.realtimeBadge': 'Real-time Data',
    'ai.assistantName': 'Maza Finance AI',
    'ai.assistantDesc': 'Financial Intelligence Assistant',

    // Footer
    'footer.tagline': 'Financial freedom starts young. We make it simple, smart, and fun.',
    'footer.features': 'Features',
    'footer.resources': 'Resources',
    'footer.download': 'Download App',
    'footer.getApp': 'Get Maza Finance on your mobile device',
    'footer.expenseTracking': 'Expense Tracking',
    'footer.aiAssistant': 'AI Finance Assistant',
    'footer.investmentGames': 'Investment Games',
    'footer.financialProjections': 'Financial Projections',
    'footer.blog': 'Blog',
    'footer.tutorials': 'Tutorials',
    'footer.financialTips': 'Financial Tips',
    'footer.helpCenter': 'Help Center',
    'footer.appStore': 'App Store',
    'footer.playStore': 'Play Store',
    'footer.copyright': '© 2024 Maza Finance. All rights reserved. Banking services provided by our partner banks.',
  },
  ms: {
    // Header
    'header.title': 'MAZA FINANCE',
    'header.subtitle': 'Penyelesaian Kewangan',
    'header.home': 'Laman Utama',
    'header.dashboard': 'Papan Pemuka',
    'header.management': 'Pengurusan',
    'header.games': 'Permainan',
    'header.pointsStore': 'Kedai Mata',
    'header.aiChat': 'Sembang AI',
    'header.news': 'Berita',
    'header.signIn': 'Log Masuk',
    'header.getStarted': 'Mula Sekarang',

    // Language switcher
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English',
    'language.malay': 'Bahasa Melayu',

    // Common
    'common.back': 'Kembali',
    'common.search': 'Cari',
    'common.loadMore': 'Muat Lagi',
    'common.viewAll': 'Lihat Semua',
    'common.readMore': 'Baca Selengkapnya',
    'common.play': 'Main',
    'common.comingSoon': 'Akan Datang',
    'common.subscribe': 'Langgan Percuma',
    'common.submit': 'Hantar',
    'common.send': 'Hantar',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.loading': 'Memuatkan...',
    'common.error': 'Berlaku ralat',
    'common.disclaimer': 'Maklumat yang diberikan hanyalah untuk tujuan pendidikan. Rujuk penasihat kewangan profesional sebelum membuat sebarang keputusan pelaburan.',
    'common.points': 'Mata',
    'common.availableToSpend': 'Tersedia untuk ditukar',
    'common.earned': 'Diperoleh',
    'common.spent': 'Digunakan',
    'common.lifetime': 'Sepanjang hayat',
    'common.streak': 'Rekod',
    'common.daily': 'Harian',
    'common.newGame': 'Permainan Baru',
    'common.help': 'Bantuan',
    'common.stats': 'Statistik',
    'common.dailyMode': 'Mod Harian',
    'common.freeMode': 'Mod Bebas',
    'common.quit': 'Keluar',
    'common.tryAgain': 'Cuba Lagi',
    'common.next': 'Seterusnya',
    'common.skip': 'Langkau',
    'common.finish': 'Selesai',
    'common.score': 'Skor',
    'common.correct': 'Betul',
    'common.incorrect': 'Salah',
    'common.yourScore': 'Skor Anda',
    'common.gamesPlayed': 'Permainan Dimainkan',
    'common.pointsCollected': 'Mata Terkumpul',
    'common.milestonesReached': 'Pencapaian Dicapai',
    'common.budget': 'Belanjawan',

    // Landing
    'landing.hero.title': 'Kuasai Wang Anda, Kuasai Masa Depan Anda',
    'landing.hero.subtitle':
      'Urus kewangan jadi mudah: catat automatik, pelaburan bijak, dan belajar melalui permainan seronok — semua dibantu AI.',
    'landing.hero.ctaPrimary': 'Mula Percuma Sekarang',
    'landing.hero.ctaSecondary': 'Lihat Cara Ia Berfungsi',

    // News
    'news.hero.badge': 'Berita Kewangan Terkini',
    'news.hero.titleLine1': 'Pasaran Bergerak Pantas?',
    'news.hero.titleLine2': 'Anda Tetap Tenang.',
    'news.hero.subtitle':
      'Berita saham, kripto, dan ekonomi yang ringkas dan mudah difahami — terus tahu apa yang perlu anda lakukan',
    'news.hero.searchPlaceholder': 'Cari berita, topik, atau kata kunci...',
    'news.hero.statArticles': 'Artikel Terkini',
    'news.hero.statReaders': 'Pembaca Aktif',
    'news.hero.statUpdates': 'Kemas Kini Masa Nyata',
    'news.breaking': 'Berita Terkini',
    'news.latest': 'Berita Terkini',
    'news.categories': 'Kategori Berita',
    'news.trending': 'Topik Hangat',
    'news.newsletter.title': 'Surat Berita Harian',
    'news.newsletter.description': 'Dapatkan ringkasan berita kewangan terus ke e-mel anda',
    'news.readMinutes': 'minit baca',
    'news.views': 'x dilihat',
    'news.takeQuiz': 'Uji pemahaman anda',
    'news.relatedGame': 'Permainan Berkaitan',
    'news.marketNews': 'Berita Pasaran',
    'news.source': 'Sumber',
    'news.noResults': 'Tiada berita ditemui. Cuba kata kunci lain.',
    'news.searchResults': 'Hasil carian',
    'news.category.stock': 'Pasaran Saham',
    'news.category.crypto': 'Cryptocurrency',
    'news.category.economy': 'Ekonomi',
    'news.category.investment': 'Pelaburan',
    'news.category.fintech': 'Fintech',
    'news.category.banking': 'Perbankan',

    // Newsletter
    'newsletter.title': 'Surat Berita Kewangan',
    'newsletter.subtitle': 'Dapatkan pandangan terkini pasaran kewangan, tip pelaburan, dan berita kewangan terus ke peti masuk anda',
    'newsletter.subscribeTitle': 'Langgan Surat Berita',
    'newsletter.subscribeDescription': 'Pilih surat berita yang ingin anda terima',
    'newsletter.emailLabel': 'Alamat E-mel',
    'newsletter.choosePlans': 'Pilih Surat Berita:',
    'newsletter.popular': 'Popular',
    'newsletter.subscribeNow': 'Langgan Sekarang',
    'newsletter.whyTitle': 'Mengapa Langgan?',
    'newsletter.ctaSubscribers': 'Pelanggan Aktif',
    'newsletter.ctaRating': 'Penilaian Surat Berita',
    'newsletter.ctaOpenRate': 'Kadar Buka',
    'newsletter.ctaForever': 'Selamanya',
    'newsletter.successTitle': 'Berjaya Langgan!',
    'newsletter.successDescription': 'Terima kasih kerana melanggan surat berita kami. E-mel pengesahan telah dihantar ke {email}',
    'newsletter.activeSubscriptions': 'Langganan Aktif:',
    'newsletter.changePlan': 'Tukar Langganan',
    'newsletter.backToNews': 'Kembali ke Berita',
    'newsletter.premiumTitle': 'Surat Berita Premium',
    'newsletter.premiumDescription': 'Naik taraf ke premium untuk analisis eksklusif, laporan penyelidikan, dan akses webinar bulanan',
    'newsletter.premiumCta': 'Ketahui Premium',
    'newsletter.termsPrefix': 'Saya bersetuju dengan',
    'newsletter.termsLink': 'syarat dan ketentuan',
    'newsletter.termsAnd': 'serta',
    'newsletter.privacyLink': 'dasar privasi',

    // Games
    'games.yourPoints': 'Mata Permainan Anda',
    'games.visitStore': 'Lawati Kedai',
    'games.popular': 'Permainan Popular',
    'games.pointsStore': 'Kedai Mata',
    'games.reward': 'Ganjaran',
    'games.achievements': 'Pencapaian Anda',
    'games.done': 'Selesai',
    'games.forcle': 'FORDLE',
    'games.forcle.desc':
      'Permainan perkataan interaktif tentang istilah kewangan. Seronok untuk menambah kosa kata kewangan anda.',
    'games.budgetMaster': 'Budget Master',
    'games.budgetMaster.desc': 'Urus belanjawan bulanan dan capai matlamat kewangan dengan permainan yang seronok',
    'games.investmentTycoon': 'Investment Tycoon',
    'games.investmentTycoon.desc': 'Bina portfolio pelaburan dan jadi jutawan maya',
    'games.savingChallenge': 'Saving Challenge',
    'games.savingChallenge.desc': 'Cabaran menabung harian dengan ganjaran menarik',
    'games.cryptoQuest': 'Crypto Quest',
    'games.cryptoQuest.desc': 'Terokai dunia kripto dengan selamat melalui simulasi',
    'games.debtDestroyer': 'Debt Destroyer',
    'games.debtDestroyer.desc': 'Strategi melunaskan hutang dengan cara yang menyeronokkan',
    'games.quizArena': 'FinQuiz Arena',
    'games.quizArena.desc': 'Uji pengetahuan kewangan anda dalam kuiz pantas',
    'games.achievement.firstInvestment': 'Pelaburan Pertama',
    'games.achievement.firstInvestment.desc': 'Buat pelaburan pertama anda',
    'games.achievement.budgetPro': 'Budget Pro',
    'games.achievement.budgetPro.desc': 'Urus belanjawan selama 30 hari',
    'games.achievement.savingStreak': 'Saving Streak',
    'games.achievement.savingStreak.desc': 'Menabung konsisten 7 hari',
    'games.achievement.quizMaster': 'Quiz Master',
    'games.achievement.quizMaster.desc': 'Jawab 100 soalan dengan betul',

    // Quiz
    'quiz.title': 'FinQuiz Arena',
    'quiz.subtitle': 'Jawab 10 soalan, buktikan anda faham wang — dan raih mata untuk ditukar hadiah.',
    'quiz.start': 'Mula Kuiz',
    'quiz.next': 'Soalan Seterusnya',
    'quiz.category': 'Kategori',
    'quiz.difficulty.easy': 'Mudah',
    'quiz.difficulty.medium': 'Sederhana',
    'quiz.difficulty.hard': 'Sukar',
    'quiz.selectCategory': 'Pilih Kategori',
    'quiz.selectDifficulty': 'Pilih Tahap Kesukaran',
    'quiz.anyCategory': 'Semua Kategori',
    'quiz.question': 'Soalan',
    'quiz.of': 'dari',
    'quiz.correctAnswer': 'Betul!',
    'quiz.wrongAnswer': 'Salah! Jawapan yang betul:',
    'quiz.completed': 'Kuiz Selesai!',
    'quiz.correctCount': 'jawapan betul',
    'quiz.pointsEarned': 'Mata diperoleh',
    'quiz.playAgain': 'Main Lagi',
    'quiz.relatedNews': 'Berita Berkaitan',
    'quiz.loadingQuestions': 'Menyediakan soalan...',
    'quiz.errorLoad': 'Gagal memuatkan soalan. Cuba lagi.',

    // Dashboard
    'dashboard.title': 'Papan Pemuka Kewangan',
    'dashboard.subtitle': 'Perbelanjaan, pelaburan, matlamat — semua wang anda di satu tempat.',
    'dashboard.expenses': 'Perbelanjaan',
    'dashboard.income': 'Pendapatan',
    'dashboard.investments': 'Pelaburan',
    'dashboard.savings': 'Simpanan',
    'dashboard.features': 'Ciri Utama',
    'dashboard.projections': 'Unjuran Kewangan',
    'dashboard.qrPayment': 'Pembayaran QR',
    'dashboard.assistant': 'Pembantu AI',

    // Management
    'management.title': 'Pengurusan Kewangan',
    'management.transactions': 'Transaksi',
    'management.addTransaction': 'Tambah Transaksi',
    'management.riskAnalysis': 'Analisis Risiko',
    'management.portfolioAnalysis': 'Analisis Portfolio',
    'management.dashboard': 'Ringkasan Kewangan',
    'management.chatbot': 'Pembantu AI',

    // Portfolio
    'portfolio.title': 'Portfolio Pelaburan',
    'portfolio.totalValue': 'Jumlah Nilai',
    'portfolio.totalReturn': 'Jumlah Pulangan',
    'portfolio.dailyChange': 'Perubahan Hari Ini',
    'portfolio.holdings': 'Pegangan',
    'portfolio.performance': 'Prestasi',

    // Savings
    'savings.title': 'Matlamat Simpanan',
    'savings.newGoal': 'Matlamat Baru',
    'savings.currentAmount': 'Jumlah Semasa',
    'savings.targetAmount': 'Sasaran',
    'savings.progress': 'Progres',
    'savings.tracker.title': 'Penjejak Simpanan',
    'savings.addEntry': 'Tambah Catatan',

    // Points
    'points.title': 'Kedai Mata',
    'points.balance': 'Baki Mata',
    'points.available': 'Mata Tersedia',
    'points.redeem': 'Tukar',
    'points.history': 'Sejarah Mata',
    'points.topUp': 'Top Up',
    'points.vouchers': 'Voucher',
    'points.purchase': 'Beli',
    'points.myVouchers': 'Voucher Saya',
    'points.noVouchers': 'Belum Ada Voucher',
    'points.noVouchersDesc': 'Beli voucher untuk melihatnya di sini',
    'points.browseVouchers': 'Lihat Voucher',
    'points.insufficientPoints': 'Mata Tidak Cukup',
    'points.confirmPurchase': 'Sahkan Pembelian',
    'points.confirmTopUp': 'Sahkan Top-Up',
    'points.processingTime': 'Masa proses: 1-24 jam',
    'points.validity': 'hari tempoh sah',
    'points.used': 'Telah Digunakan',
    'points.expired': 'Tamat Tempoh',
    'points.daysLeft': 'hari berbaki',
    'points.useVoucher': 'Gunakan Voucher',
    'points.alreadyUsed': 'Telah Digunakan',

    // AI Chat
    'ai.title': 'Pembantu Kewangan AI',
    'ai.subtitle': 'Rujuk kewangan dan pelaburan dengan AI yang menyeluruh dan masa nyata',
    'ai.placeholder': 'Tanya tentang pelaburan, saham, kripto, perancangan kewangan...',
    'ai.quickTitle': 'Soalan Pantas',
    'ai.analyzing': 'AI sedang menganalisis...',
    'ai.online': 'Dalam Talian',
    'ai.poweredBy': 'Dikuasakan AI Lanjutan',
    'ai.welcome':
      'Selamat datang ke MAZA Finance AI!\n\nSaya pembantu AI kewangan anda, bersedia membantu dengan:\n\n- Analisis Pelaburan & Saham\n- Perancangan Kewangan Peribadi\n- Kripto & Dagangan\n- Analisis Portfolio\n- Strategi Pelaburan Jangka Panjang\n\nApa yang anda ingin tanyakan hari ini?',
    'ai.quick.stocks': 'Analisis saham BBRI terkini',
    'ai.quick.currency': 'Kadar tukaran USD ke IDR hari ini',
    'ai.quick.portfolio': 'Strategi kepelbagaian portfolio',
    'ai.quick.news': 'Berita pasaran modal terkini',
    'ai.conversations': 'Perbualan',
    'ai.newConversation': 'Perbualan Baharu',
    'ai.signInTitle': 'Sila Log Masuk',
    'ai.signInPrompt': 'Anda perlu log masuk untuk menggunakan Pembantu AI Kewangan.',
    'ai.realtimeBadge': 'Data Masa Nyata',
    'ai.assistantName': 'Maza Finance AI',
    'ai.assistantDesc': 'Pembantu Kepintaran Kewangan',

    // Footer
    'footer.tagline': 'Kebebasan kewangan bermula sejak muda. Kami buat ia mudah, bijak, dan seronok.',
    'footer.features': 'Ciri',
    'footer.resources': 'Sumber',
    'footer.download': 'Muat Turun Apl',
    'footer.getApp': 'Dapatkan Maza Finance pada peranti anda',
    'footer.expenseTracking': 'Penjejakan Perbelanjaan',
    'footer.aiAssistant': 'Pembantu Kewangan AI',
    'footer.investmentGames': 'Permainan Pelaburan',
    'footer.financialProjections': 'Unjuran Kewangan',
    'footer.blog': 'Blog',
    'footer.tutorials': 'Tutorial',
    'footer.financialTips': 'Tip Kewangan',
    'footer.helpCenter': 'Pusat Bantuan',
    'footer.appStore': 'App Store',
    'footer.playStore': 'Play Store',
    'footer.copyright': '© 2024 Maza Finance. Hak cipta terpelihara. Perkhidmatan perbankan disediakan oleh bank rakan kongsi kami.',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('id')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && ['id', 'en', 'ms'].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language)
    // Update document language attribute
    document.documentElement.lang = language
  }, [language])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}